server:
  servlet:
    context-path: /shcms/v1/api
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/shcms_backend
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    banner-mode: off

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /status
      exposure:
        include: "health,info"
        exclude: "health"

# This will be replaced with the Maven version
info:
  application:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'

# Reduce logging level. Set logging level to warn
logging:
  level:
    root: warn